steps:
  # build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ 'build', '-t', '${_IMAGE_NAME}', '.' ]
  # push
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "${_IMAGE_NAME}"]
  # deploy
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_IMAGE_NAME}",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

substitutions:
  _SERVICE_NAME: "container-deploy"
  _IMAGE_NAME: "asia.gcr.io/btc-trade-330602/test/${SHORT_SHA}"

images:
  - "${_IMAGE_NAME}"